# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"
  
  config.vm.network "forwarded_port", guest: 80, host: 8080
  
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "apache" > /etc/hostname
    sudo yum install vim httpd -y
    sudo cp /etc/httpd/conf/httpd.conf ~/httpd.conf.bak
    sudo bash -c "curl https://raw.githubusercontent.com/picatz/skynet/master/examples/centos7_apache/httpd.conf > /etc/httpd/conf/httpd.conf"
    sudo bash -c "echo 'Made with ♥ by picat' > /var/www/html/index.html"
    sudo systemctl enable httpd
    sudo systemctl start httpd
    curl localhost
  SHELL
end
